const Fproducts=[
    {
        "id":1,
        "img":"src/assets/veg-1.png",
        "text":"Beetroot",
        "discount":20,
        "gram":200,
        "rate":50,
        "dis":"Beetroot is a root vegetable also known as red beet, table beet, garden beet, or just beet.",
        "images":{
            img1:"src/assets/veg-1.png",
            img2:"src/assets/vegetables/beetroot-2.png",
            img3:"src/assets/vegetables/beetroot-3.png",
            img4:"src/assets/vegetables/beetroot-4.png",
            img5:"src/assets/vegetables/beetroot-5.png",
        }
    },
    {
        "id":2,
        "img":"src/assets/meat-1.png",
        "text":"Beef Steaks",
        "discount":10,
        "gram":500,
        "rate":350,
        "dis":"It's exceptionally rich in high-quality protein, vitamins, and minerals. Therefore, it may improve muscle growth and maintenance, as well as exercise performance.",
        "images":{
            img1:"src/assets/meat-1.png",
            img2:"src/assets/meat/meat-2.png",
            img3:"src/assets/meat/meat-3.png",
            img4:"src/assets/meat/meat-4.png",
            img5:"src/assets/meat/meat-5.png",
        }
    },
    {
        "id":3,
        "img":"src/assets/egg.png",
        "text":"Egg",
        "discount":5,
        "gram":30,
        "rate":20,
        "dis":"Eggs are packed full of high-quality protein, making them ideal as part of many different dietary patterns that can assist people in managing their weight",
        "images":{
            img1:"src/assets/egg.png",
            img2:"src/assets/egg/egg-2.png",
            img3:"src/assets/egg/egg-3.png",
            img4:"src/assets/egg/egg-4.png",
            img5:"src/assets/egg/egg-5.png",
        }
    },
    {
        "id":4,
        "img":"src/assets/milk-1.png",
        "text":"Milk",
        "discount":7,
        "gram":100,
        "rate":40,
        "dis":"Milk is rich in vitamin D, calcium, and phosphorus, essential for building and maintaining strong bones. Calcium is the main mineral that makes up your bones.",
        "images":{
            img1:"src/assets/milk-1.png",
            img2:"src/assets/milk/milk-2.png",
            img3:"src/assets/milk/milk-3.png",
            img4:"src/assets/milk/milk-4.png",
            img5:"src/assets/milk/milk-5.png",
        }
    },
    {
        "id":5,
        "img":"src/assets/dry-1.png",
        "text":"Almond",
        "discount":15,
        "gram":400,
        "rate":650,
        "dis":" Almonds have both calcium and phosphorus, which are good for bone health. Almonds seem to help curb blood sugar spikes after meals, which is key for people with diabetes.",
        "images":{
            img1:"src/assets/dry-1.png",
            img2:"src/assets/dry/almond-2.png",
            img3:"src/assets/dry/almond-3.png",
            img4:"src/assets/dry/almond-4.png",
            img5:"src/assets/dry/almond-5.png",
        }
    },
    {
        "id":6,
        "img":"src/assets/fruit-1.png",
        "text":"Mango",
        "discount":45,
        "gram":500,
        "rate":250,
        "dis":"Mango is rich in vitamins, minerals, and antioxidants, and it has been associated with many health benefits, including potential anticancer effects, as well as improved immunity and digestive and eye health.",
        "images":{
            img1:"src/assets/fruit-1.png",
            img2:"src/assets/fruits/mango-2.png",
            img3:"src/assets/fruits/mango-3.png",
            img4:"src/assets/fruits/mango-4.png",
            img5:"src/assets/fruits/mango-5.png",
        }
    },
    {
        "id":7,
        "img":"src/assets/veg-2.png",
        "text":"Onion",
        "discount":15,
        "gram":500,
        "rate":450,
        "dis":"Onions may provide potential health benefits. These may include reducing the risk of several types of cancer, improving mood, and maintaining skin and hair health.",
        "images":{
            img1:"src/assets/veg-2.png",
            img2:"src/assets/vegetables/onion-2.png",
            img3:"src/assets/vegetables/onion-3.png",
            img4:"src/assets/vegetables/onion-4.png",
            img5:"src/assets/vegetables/onion-5.png",
        }
    },
    {
        "id":8,
        "img":"src/assets/dry-2.png",
        "text":"Date",
        "discount":8,
        "gram":500,
        "rate":470,
        "dis":"Almonds have both calcium and phosphorus, which are good for bone health. Almonds seem to help curb blood sugar spikes after meals, which is key for people with diabetes.",
        "images":{
            img1:"src/assets/dry-2.png",
            img2:"src/assets/dry/dry-2.png",
            img3:"src/assets/dry/dry-3.png",
            img4:"src/assets/dry/dry-4.png",
            img5:"src/assets/dry/dry-5.png",
        }
    },
    {
        "id":9,
        "img":"src/assets/meat-2.png",
        "text":"Fish Meat",
        "discount":18,
        "gram":500,
        "rate":170,
        "dis":"Fish is rich in calcium and phosphorus and a great source of minerals, such as iron, zinc, iodine, magnesium, and potassium.",
        "images":{
            img1:"src/assets/meat-2.png",
            img2:"src/assets/meat/fish-2.png",
            img3:"src/assets/meat/fish-3.png",
            img4:"src/assets/meat/fish-4.png",
            img5:"src/assets/meat/fish-5.png",
        }
    },
    {
        "id":10,
        "img":"src/assets/fruit-2.png",
        "text":"Orange",
        "discount":27,
        "gram":500,
        "rate":470,
        "dis":"Oranges are a treasure trove of nutrients and protective plant compounds, including vitamins, minerals, and antioxidants. Studies show that consuming oranges regularly may benefit your health in several ways.",
        "images":{
            img1:"src/assets/fruit-2.png",
            img2:"src/assets/fruits/orange-2.png",
            img3:"src/assets/fruits/orange-3.png",
            img4:"src/assets/fruits/orange-4.png",
            img5:"src/assets/fruits/orange-5.png",
        }
    }
];

export default Fproducts;